global using CommunityToolkit.Mvvm.ComponentModel;
global using CommunityToolkit.Mvvm.Input;
global using System.Collections.ObjectModel;
global using System.Diagnostics;
global using Notes.Models;
global using Notes.ViewModels;
global using Microsoft.Extensions.Logging;
global using Notes.Services;
global using Notes.Views;